// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApF74IiHVLh60I-Bw-uz_4zPtyVZsyn2E',
    appId: '1:13903696616:web:5861c37ca4e95346eb2f5d',
    messagingSenderId: '13903696616',
    projectId: 'stage-dev-d5555',
    authDomain: 'stage-dev-d5555.firebaseapp.com',
    storageBucket: 'stage-dev-d5555.firebasestorage.app',
    measurementId: 'G-BJ0KQQYMGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNc1Len5MdRFy4_ckJxIrzc-jnBkbGOks',
    appId: '1:13903696616:android:6ebd7cb791d856d8eb2f5d',
    messagingSenderId: '13903696616',
    projectId: 'stage-dev-d5555',
    storageBucket: 'stage-dev-d5555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGdxefBCGqhYBiIJn3k6hjqjJK5n-oynA',
    appId: '1:13903696616:ios:8022817ed4fa0f20eb2f5d',
    messagingSenderId: '13903696616',
    projectId: 'stage-dev-d5555',
    storageBucket: 'stage-dev-d5555.firebasestorage.app',
    iosBundleId: 'com.endorodrigo.tirandoFactos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGdxefBCGqhYBiIJn3k6hjqjJK5n-oynA',
    appId: '1:13903696616:ios:8022817ed4fa0f20eb2f5d',
    messagingSenderId: '13903696616',
    projectId: 'stage-dev-d5555',
    storageBucket: 'stage-dev-d5555.firebasestorage.app',
    iosBundleId: 'com.endorodrigo.tirandoFactos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApF74IiHVLh60I-Bw-uz_4zPtyVZsyn2E',
    appId: '1:13903696616:web:9f59eb56992682cceb2f5d',
    messagingSenderId: '13903696616',
    projectId: 'stage-dev-d5555',
    authDomain: 'stage-dev-d5555.firebaseapp.com',
    storageBucket: 'stage-dev-d5555.firebasestorage.app',
    measurementId: 'G-3L8R3VF306',
  );
}
